package com.sephuan.quicklaunch.ui.theme

import androidx.compose.ui.graphics.Color

// Blue scheme
val BlueLightPrimary = Color(0xFF1A56DB)
val BlueLightOnPrimary = Color(0xFFFFFFFF)
val BlueLightPrimaryContainer = Color(0xFFD8E2FF)
val BlueLightOnPrimaryContainer = Color(0xFF001A42)
val BlueLightSecondary = Color(0xFF565F71)
val BlueLightOnSecondary = Color(0xFFFFFFFF)
val BlueLightSecondaryContainer = Color(0xFFDAE2F9)
val BlueLightOnSecondaryContainer = Color(0xFF131C2B)
val BlueLightTertiary = Color(0xFF705575)
val BlueLightOnTertiary = Color(0xFFFFFFFF)
val BlueLightTertiaryContainer = Color(0xFFFAD8FE)
val BlueLightOnTertiaryContainer = Color(0xFF28132E)
val BlueLightBackground = Color(0xFFF9F9FF)
val BlueLightOnBackground = Color(0xFF191C20)
val BlueLightSurface = Color(0xFFF9F9FF)
val BlueLightOnSurface = Color(0xFF191C20)
val BlueLightSurfaceVariant = Color(0xFFE0E2EC)
val BlueLightOnSurfaceVariant = Color(0xFF44474E)

val BlueDarkPrimary = Color(0xFFADC6FF)
val BlueDarkOnPrimary = Color(0xFF002D6A)
val BlueDarkPrimaryContainer = Color(0xFF004394)
val BlueDarkOnPrimaryContainer = Color(0xFFD8E2FF)
val BlueDarkSecondary = Color(0xFFBEC6DC)
val BlueDarkOnSecondary = Color(0xFF283041)
val BlueDarkSecondaryContainer = Color(0xFF3E4759)
val BlueDarkOnSecondaryContainer = Color(0xFFDAE2F9)
val BlueDarkTertiary = Color(0xFFDDBCE1)
val BlueDarkOnTertiary = Color(0xFF3F2845)
val BlueDarkTertiaryContainer = Color(0xFF573F5C)
val BlueDarkOnTertiaryContainer = Color(0xFFFAD8FE)
val BlueDarkBackground = Color(0xFF111318)
val BlueDarkOnBackground = Color(0xFFE2E2E9)
val BlueDarkSurface = Color(0xFF111318)
val BlueDarkOnSurface = Color(0xFFE2E2E9)
val BlueDarkSurfaceVariant = Color(0xFF44474E)
val BlueDarkOnSurfaceVariant = Color(0xFFC4C6D0)

// Green scheme
val GreenLightPrimary = Color(0xFF0B6B43)
val GreenLightOnPrimary = Color(0xFFFFFFFF)
val GreenLightPrimaryContainer = Color(0xFFA3F5BB)
val GreenLightOnPrimaryContainer = Color(0xFF002112)
val GreenLightSecondary = Color(0xFF4E6354)
val GreenLightOnSecondary = Color(0xFFFFFFFF)
val GreenLightSecondaryContainer = Color(0xFFD1E8D5)
val GreenLightOnSecondaryContainer = Color(0xFF0C1F14)
val GreenLightTertiary = Color(0xFF3C6472)
val GreenLightOnTertiary = Color(0xFFFFFFFF)
val GreenLightTertiaryContainer = Color(0xFFBFE9FA)
val GreenLightOnTertiaryContainer = Color(0xFF001F28)

val GreenDarkPrimary = Color(0xFF87D9A0)
val GreenDarkOnPrimary = Color(0xFF00391F)
val GreenDarkPrimaryContainer = Color(0xFF00522F)
val GreenDarkOnPrimaryContainer = Color(0xFFA3F5BB)
val GreenDarkSecondary = Color(0xFFB5CCBA)
val GreenDarkOnSecondary = Color(0xFF213528)
val GreenDarkSecondaryContainer = Color(0xFF374B3E)
val GreenDarkOnSecondaryContainer = Color(0xFFD1E8D5)
val GreenDarkTertiary = Color(0xFFA4CDDE)
val GreenDarkOnTertiary = Color(0xFF043542)
val GreenDarkTertiaryContainer = Color(0xFF224C5A)
val GreenDarkOnTertiaryContainer = Color(0xFFBFE9FA)

// Orange scheme
val OrangeLightPrimary = Color(0xFF8D4C00)
val OrangeLightOnPrimary = Color(0xFFFFFFFF)
val OrangeLightPrimaryContainer = Color(0xFFFFDCBF)
val OrangeLightOnPrimaryContainer = Color(0xFF2D1500)
val OrangeLightSecondary = Color(0xFF735A42)
val OrangeLightOnSecondary = Color(0xFFFFFFFF)
val OrangeLightSecondaryContainer = Color(0xFFFEDDBF)
val OrangeLightOnSecondaryContainer = Color(0xFF281805)
val OrangeLightTertiary = Color(0xFF54633D)
val OrangeLightOnTertiary = Color(0xFFFFFFFF)
val OrangeLightTertiaryContainer = Color(0xFFD7E9B8)
val OrangeLightOnTertiaryContainer = Color(0xFF131F03)

val OrangeDarkPrimary = Color(0xFFFFB77A)
val OrangeDarkOnPrimary = Color(0xFF4C2600)
val OrangeDarkPrimaryContainer = Color(0xFF6B3900)
val OrangeDarkOnPrimaryContainer = Color(0xFFFFDCBF)
val OrangeDarkSecondary = Color(0xFFE2C1A4)
val OrangeDarkOnSecondary = Color(0xFF412C18)
val OrangeDarkSecondaryContainer = Color(0xFF5A422D)
val OrangeDarkOnSecondaryContainer = Color(0xFFFEDDBF)
val OrangeDarkTertiary = Color(0xFFBBCD9E)
val OrangeDarkOnTertiary = Color(0xFF273513)
val OrangeDarkTertiaryContainer = Color(0xFF3D4C28)
val OrangeDarkOnTertiaryContainer = Color(0xFFD7E9B8)

// Rose scheme
val RoseLightPrimary = Color(0xFFBA005C)
val RoseLightOnPrimary = Color(0xFFFFFFFF)
val RoseLightPrimaryContainer = Color(0xFFFFD9E2)
val RoseLightOnPrimaryContainer = Color(0xFF3E001C)
val RoseLightSecondary = Color(0xFF725763)
val RoseLightOnSecondary = Color(0xFFFFFFFF)
val RoseLightSecondaryContainer = Color(0xFFFCD9E8)
val RoseLightOnSecondaryContainer = Color(0xFF29151F)
val RoseLightTertiary = Color(0xFF7F5633)
val RoseLightOnTertiary = Color(0xFFFFFFFF)
val RoseLightTertiaryContainer = Color(0xFFFFDCC1)
val RoseLightOnTertiaryContainer = Color(0xFF301500)

val RoseDarkPrimary = Color(0xFFFFB1C8)
val RoseDarkOnPrimary = Color(0xFF65002F)
val RoseDarkPrimaryContainer = Color(0xFF8E0045)
val RoseDarkOnPrimaryContainer = Color(0xFFFFD9E2)
val RoseDarkSecondary = Color(0xFFDFBECB)
val RoseDarkOnSecondary = Color(0xFF402935)
val RoseDarkSecondaryContainer = Color(0xFF58404B)
val RoseDarkOnSecondaryContainer = Color(0xFFFCD9E8)
val RoseDarkTertiary = Color(0xFFEFBD96)
val RoseDarkOnTertiary = Color(0xFF49290B)
val RoseDarkTertiaryContainer = Color(0xFF633F1E)
val RoseDarkOnTertiaryContainer = Color(0xFFFFDCC1)

// Violet scheme
val VioletLightPrimary = Color(0xFF6B44C2)
val VioletLightOnPrimary = Color(0xFFFFFFFF)
val VioletLightPrimaryContainer = Color(0xFFEBDCFF)
val VioletLightOnPrimaryContainer = Color(0xFF24005C)
val VioletLightSecondary = Color(0xFF635B70)
val VioletLightOnSecondary = Color(0xFFFFFFFF)
val VioletLightSecondaryContainer = Color(0xFFE9DEF8)
val VioletLightOnSecondaryContainer = Color(0xFF1F182B)
val VioletLightTertiary = Color(0xFF7D5260)
val VioletLightOnTertiary = Color(0xFFFFFFFF)
val VioletLightTertiaryContainer = Color(0xFFFFD8E4)
val VioletLightOnTertiaryContainer = Color(0xFF31101D)

val VioletDarkPrimary = Color(0xFFD0BCFF)
val VioletDarkOnPrimary = Color(0xFF3C0090)
val VioletDarkPrimaryContainer = Color(0xFF5526A8)
val VioletDarkOnPrimaryContainer = Color(0xFFEBDCFF)
val VioletDarkSecondary = Color(0xFFCDC2DC)
val VioletDarkOnSecondary = Color(0xFF342D40)
val VioletDarkSecondaryContainer = Color(0xFF4A4458)
val VioletDarkOnSecondaryContainer = Color(0xFFE9DEF8)
val VioletDarkTertiary = Color(0xFFEFB8C8)
val VioletDarkOnTertiary = Color(0xFF4A2532)
val VioletDarkTertiaryContainer = Color(0xFF633B48)
val VioletDarkOnTertiaryContainer = Color(0xFFFFD8E4)

// Teal scheme
val TealLightPrimary = Color(0xFF006B5C)
val TealLightOnPrimary = Color(0xFFFFFFFF)
val TealLightPrimaryContainer = Color(0xFF80F8E2)
val TealLightOnPrimaryContainer = Color(0xFF00201B)
val TealLightSecondary = Color(0xFF4A635E)
val TealLightOnSecondary = Color(0xFFFFFFFF)
val TealLightSecondaryContainer = Color(0xFFCCE8E1)
val TealLightOnSecondaryContainer = Color(0xFF051F1B)
val TealLightTertiary = Color(0xFF416276)
val TealLightOnTertiary = Color(0xFFFFFFFF)
val TealLightTertiaryContainer = Color(0xFFC4E7FF)
val TealLightOnTertiaryContainer = Color(0xFF001E2C)

val TealDarkPrimary = Color(0xFF60DBC6)
val TealDarkOnPrimary = Color(0xFF00382F)
val TealDarkPrimaryContainer = Color(0xFF005145)
val TealDarkOnPrimaryContainer = Color(0xFF80F8E2)
val TealDarkSecondary = Color(0xFFB1CCC6)
val TealDarkOnSecondary = Color(0xFF1C3530)
val TealDarkSecondaryContainer = Color(0xFF324C46)
val TealDarkOnSecondaryContainer = Color(0xFFCCE8E1)
val TealDarkTertiary = Color(0xFFA8CBE3)
val TealDarkOnTertiary = Color(0xFF0F3445)
val TealDarkTertiaryContainer = Color(0xFF284A5D)
val TealDarkOnTertiaryContainer = Color(0xFFC4E7FF)

// Amber scheme
val AmberLightPrimary = Color(0xFF8C5300)
val AmberLightOnPrimary = Color(0xFFFFFFFF)
val AmberLightPrimaryContainer = Color(0xFFFFDDB6)
val AmberLightOnPrimaryContainer = Color(0xFF2D1700)
val AmberLightSecondary = Color(0xFF715A41)
val AmberLightOnSecondary = Color(0xFFFFFFFF)
val AmberLightSecondaryContainer = Color(0xFFFCDDBD)
val AmberLightOnSecondaryContainer = Color(0xFF271805)
val AmberLightTertiary = Color(0xFF53653A)
val AmberLightOnTertiary = Color(0xFFFFFFFF)
val AmberLightTertiaryContainer = Color(0xFFD6EBB6)
val AmberLightOnTertiaryContainer = Color(0xFF122003)

val AmberDarkPrimary = Color(0xFFFFB870)
val AmberDarkOnPrimary = Color(0xFF4B2A00)
val AmberDarkPrimaryContainer = Color(0xFF6A3E00)
val AmberDarkOnPrimaryContainer = Color(0xFFFFDDB6)
val AmberDarkSecondary = Color(0xFFE0C1A2)
val AmberDarkOnSecondary = Color(0xFF3F2C16)
val AmberDarkSecondaryContainer = Color(0xFF58422B)
val AmberDarkOnSecondaryContainer = Color(0xFFFCDDBD)
val AmberDarkTertiary = Color(0xFFBACF9C)
val AmberDarkOnTertiary = Color(0xFF263612)
val AmberDarkTertiaryContainer = Color(0xFF3C4D27)
val AmberDarkOnTertiaryContainer = Color(0xFFD6EBB6)

// Indigo scheme
val IndigoLightPrimary = Color(0xFF3F4F9E)
val IndigoLightOnPrimary = Color(0xFFFFFFFF)
val IndigoLightPrimaryContainer = Color(0xFFDDE1FF)
val IndigoLightOnPrimaryContainer = Color(0xFF000E57)
val IndigoLightSecondary = Color(0xFF5A5D72)
val IndigoLightOnSecondary = Color(0xFFFFFFFF)
val IndigoLightSecondaryContainer = Color(0xFFDFE1F9)
val IndigoLightOnSecondaryContainer = Color(0xFF171A2C)
val IndigoLightTertiary = Color(0xFF76546E)
val IndigoLightOnTertiary = Color(0xFFFFFFFF)
val IndigoLightTertiaryContainer = Color(0xFFFFD7F2)
val IndigoLightOnTertiaryContainer = Color(0xFF2C1229)

val IndigoDarkPrimary = Color(0xFFB8C4FF)
val IndigoDarkOnPrimary = Color(0xFF07226C)
val IndigoDarkPrimaryContainer = Color(0xFF263884)
val IndigoDarkOnPrimaryContainer = Color(0xFFDDE1FF)
val IndigoDarkSecondary = Color(0xFFC3C5DD)
val IndigoDarkOnSecondary = Color(0xFF2C2F42)
val IndigoDarkSecondaryContainer = Color(0xFF424659)
val IndigoDarkOnSecondaryContainer = Color(0xFFDFE1F9)
val IndigoDarkTertiary = Color(0xFFE4BAD5)
val IndigoDarkOnTertiary = Color(0xFF44263F)
val IndigoDarkTertiaryContainer = Color(0xFF5D3C56)
val IndigoDarkOnTertiaryContainer = Color(0xFFFFD7F2)
